services:

  eureka-discovery-server:
    build:
      context: ./eureka-discovery-server
      dockerfile: Dockerfile
    container_name: eureka-discovery-server
    hostname: eureka-discovery-server
    ports:
      - 8761:8761
    environment:
      - DISCOVERY_SERVER_URL=http://eureka-discovery-server:8761/eureka
      - PORT=8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    hostname: api-gateway
    ports:
      - 8765:8765
    environment:
      - DISCOVERY_SERVER_URL=http://eureka-discovery-server:8761/eureka
      - PORT=8765
    networks:
      - microservices-network
    depends_on:
      eureka-discovery-server:
        condition: service_healthy

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    hostname: user-service
    ports:
      - 8081:8080
    environment:
      - DISCOVERY_SERVER_URL=http://eureka-discovery-server:8761/eureka
      - PORT=8080
    networks:
      - microservices-network
    depends_on:
      eureka-discovery-server:
        condition: service_healthy

networks:
  microservices-network:
    driver: bridge